data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  AzureWebJobsStorage: e0F6dXJlV2ViSm9ic1N0b3JhZ2V9
apiVersion: v1
kind: Secret
metadata:
  name: azure-blob
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-blob
  namespace: default
  labels:
    app: azure-blob
spec:
  selector:
    matchLabels:
      app: azure-blob
  template:
    metadata:
      labels:
        app: azure-blob
    spec:
      containers:
      - name: azure-blob
        image: shikhajain0502/azure-blob
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: azure-blob
        envFrom:
        - secretRef:
            name: azure-blob
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-blob
  namespace: default
  labels:
    deploymentName: azure-blob
spec:
  scaleTargetRef:
    deploymentName: azure-blob-trigger
  minReplicaCount: 1
  maxReplicaCount: 10  
  triggers:
  - type: azure-blob-trigger
    metadata:
      blobContainerName: blob-trigger-bucket
      blobCount: "5" # default 5
      blobPrefix: blobsubpath # Default : ""
      blobDelimiter: "/" # Default: "/"
      name: myblob
      type: blobTrigger
      direction: in
      path: blob-trigger-bucket/{name}
      connection: AzureWebJobsStorage
---

